### ISSUE TITLE
docs: Mistake in the guide documentation

### ISSUE THREAD

**Issue by aitijhyasarkar** [wrappid/core#102]
**Describe the bug**
Table content of the variant prop of CoreAvatarGroup is buggy, related to #97 

**Expected behavior**
All documentations must be thoroughly checked for any silly mistakes like these. Documentations must showcase professionalism.

**Screenshots**
![875537fa-0fe1-43cc-94b2-1457f76507fb{done}](https://github.com/wrappid/core/assets/91305796/7750dd59-6e8b-45eb-8ba0-57f1131bd956)

**Additional context**

- Documentation URLs:
    - http://127.0.0.1:xxxx/guide/components

*Note:* Ensure that the placeholders xxxx are replaced with the hosted port number.

**Comment by techoneel** [comment]
This issue is redundant issue to #101 
so closing this issue as invalid issue
