### ISSUE TITLE
bugfix: Collapse not working in the menu

### ISSUE THREAD

**Issue by Edithmark42** [wrappid/core#103]
onClick Collapse not working in the menu (Setup)

**Expected behavior**
It should collapse on clicking

**Screenshots**
![image](https://github.com/wrappid/core/assets/58048663/b79a21ec-acea-4d08-8d75-f622530152b0)

**Comment by Edithmark42** [comment]
This issue was fixed and merged to development pull req #104

**Comment by techoneel** [comment]
this issue is fixed, henceforth the issue is no longer valid.
