### ISSUE TITLE
bugfix: removed Auth object from CoreClases.js 

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/core#133]
**Describe the bug**
Have to remove 'Auth' style object from CoreClasses.js and it will be shifted to ModuleClasses.js of auth-module.

**To Reproduce**

**Expected behavior**

**Stack Trace**
The stack trace of the bug if any.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techoneel** [comment]
issue resolved with the auth related classes and styles moved from core package to auth-module in wrappid/auth-module#36 and it is removed from core
