### ISSUE TITLE
enhancement: delivery oriented fix

### ISSUE THREAD

**Issue by techoneel** [wrappid/core#183]
- [x] add defaulValidEvents props in sanatizeCompProps function 
- [x] CoreRoutes API calls multiple time 
- [x] activate StrictMode in dev mode only
- [x] Authentication related changes
- [x] AppContainerLayout working
- [x] RolePermission menu generation in menuReducer.
- [x]  Login pages to dashboard login not working (splash component navigation problem)
- [x]  Logout navigation not working
- [x] Left drawer click not working (valid props missing toggleDrawer in coreDrawer)
- [x] profile popover navigation links (view profile, settings) not working. (route registry from context coming empty in CoreProfilePopOver component )
- [x] Settings page is not having CoreTabs (Core tabs component related problem)
- [x] Register page not following auth layout i.e. width becoming full page.
- [x] @wrappid/core version is 0.447 is coming when running setup. This is missing a major update available in 0.0.452.
- [x] reset form state while changing form state

**Comment by sumanta-m** [comment]
- [ ] Login pages to dashboard login not working (splash component navigation problem)
- [ ] Logout navigation not working
- [ ] Left drawer click not working (valid props missing toggleDrawer in coreDrawer)
- [ ] profile popover navigation links (view profile, settings) not working.  (route registry from context coming empty in CoreProfilePopOver component )
- [ ] Settings page is not having CoreTabs (Core tabs component related problem)
- [ ] Register page not following auth layout i.e. width becoming full page.

**Comment by sumanta-m** [comment]
- [ ] @wrappid/core version is 0.447 is coming when running setup. This is missing a major update available in 0.0.452.

**Comment by techoneel** [comment]
closing this since all are resolved
