### ISSUE TITLE
Failed to load plugin 'sort-keys-fix' declared in '.eslintrc.js'

### ISSUE THREAD

**Issue by chirag-uemk** [wrappid/core#226]
**Describe the bug**

Getting the following error on screen once I've created a application from wrappid-app template and setup the project with toolkit command and start the project.

Failed to load plugin 'sort-keys-fix' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-sort-keys-fix'

**To Reproduce**

```
1. wr init <project-name>
2. wr setup web
3. wr start web
```

See error

**Expected behavior**

A default, boilerplate application should be running. 

**Stack Trace**

- /home/chirag/tes2-app/.wrappid/runtime/web/config/__placeholder__.js

**Screenshots**

![image](https://github.com/wrappid/core/assets/140333955/8408daa9-a201-4377-a3f9-26054e89bc18)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Brave [Version 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit))
- Version: @wrappid/core 0.0.469

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by techoneel** [comment]
closing this issue since this issue had been fixed long ago.
