### ISSUE TITLE
enhancement: CoreCustomTabs's CoreTabHead styling with props

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/core#233]
**Is your feature request related to a problem? Please describe.**
Currently styling TabHead is not possible via props.

**Describe the solution you'd like**
Add tabHeadClasses props to CoreCustomTabs for CoreTabHeads, just like tabPanelClasses for CoreTabPanel.
Pass tabHeadClasses to CoreTabHead's styleComponents props

**Additional context**
- [x] wrappid/native-web#74
This issue is related with [wrappid/native-web](https://www.github.com/wrappid/native-web) for web app

**Comment by techoneel** [comment]
after discussing with @anantakumarghosh the issue is no longer present in the system.
