### ISSUE TITLE
bugfix: OTP in CoreOtpInput

### ISSUE THREAD

**Issue by PritamBag** [wrappid/core#270]
**Describe the bug**
In the CoreOtpInput component, if we want to delete or remove one character from the OTP, it first selects this particular character and then deletes or removes it. I believe the selection looks bad and can negatively impact the user experience. Additionally, pasting the OTP using Ctrl+V is not working.

**To Reproduce**
1. Go to 'https://demo.wrappid.dev/checkuserexist or http://localhost:3000/checkuserexist' fill the details
2. It should redirect to 'https://demo.wrappid.dev/register or http://localhost:3000/register'
3. After entering OTP in input, press backspace
4. Try to paste OTP using ctrl+v

**Expected behavior**
1. Deleting a character should remove it directly without selecting it first.
2. Pasting the OTP using Ctrl+V should work seamlessly.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 126.0.6478.128

![image](https://github.com/user-attachments/assets/bbb7c9be-c016-4996-93cd-93f78a1a3cc0)

**Comment by techoneel** [comment]
this issue got resolved and no further issue reported regarding this issue so closing this issue kudos 👍 @PritamBag
