### ISSUE TITLE
Doesn't contain type of list that present in HTML

### ISSUE THREAD

**Issue by arkaprota** [wrappid/core#272]
**Description**
The List is present in wrappid as CoreList but it doesn't contain ordered, unordered list and description list.

**Solution**
Create a Different component for each list which name will be
CoreUL
CoreOL
CoreLi
CoreDL
CoreDT
CoreDD

**Reference**

https://www.w3schools.com/html/html_lists.asp

**Image Reference**
![Screenshot 2024-07-22 121313](https://github.com/user-attachments/assets/a1f63c5a-df1c-4d81-a27b-35b7594e49ff)

**Comment by techoneel** [comment]
@arkaprota please give an update on the issue I think we've changed the basic design of the feature please refer if you created an another issue else please update this issue description.

**Comment by arkaprota** [comment]
there are few changes in idea so there is no need of creating 
CoreUL
CoreOL
CoreLi
CoreDL
CoreDT
CoreDD

@techoneel
