### ISSUE TITLE
bug: CoreTooltip not working

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/core#290]
**Describe the bug**
CoreTooltip is not working. Tooltip not showing on hover

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anantakumarghosh** [comment]
This issue is of wrappid/native-web for web browser, and wrappid/native-mobile for mobile app.

For web, the issue is tracked here: wrappid/native-web#97

**Comment by PritamIT2023** [comment]
Closing as done
