### ISSUE TITLE
bug: CoreAvatarGroup not working in mobile.

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/core#61]
**Describe the bug**
CoreAvatarGroup not working in mobile (only working in web).

**To Reproduce**

**Expected behavior**
CoreAvatarGroup should work in mobile too.

**Stack Trace**
The stack trace of the bug if any.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techoneel** [comment]
Update the issue and create platform specific issues if there are any and give reference.

**Comment by irkfaisal** [comment]
issue moved to native-mobile, ref: #https://github.com/wrappid/native-mobile/issues/60
