### ISSUE TITLE
enhancement: Add valid props in CoreLink

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/core#62]
**Is your feature request related to a problem? Please describe.**
Add valid props in CoreLink and sanitize props that should work in mobile too.

**Describe the solution you'd like**
 

**Describe alternatives you've considered**

**Additional context**

**Comment by irkfaisal** [comment]
vaid props is added for CoreLink, component is working on web perfectly but not in mobile.

**Comment by techoneel** [comment]
Create a separate issue in native-mobile and give the reference here and close the if you think no more changes is required in CoreLink

**Comment by irkfaisal** [comment]
created a separate issue in native-mobile #https://github.com/wrappid/native-mobile/issues/59
