### ISSUE TITLE
enchancement: Core component to display table of contents for all headings in the single page.

### ISSUE THREAD

**Issue by saifalamkhan373** [wrappid/core#65]
## Description
Create a Core component which will display a menu like table of contents for all headings in the single page.

**Comment by samhere17** [comment]
Related Issues:

wrappid/guide-module#11
wrappid/guide-module#12
wrappid/guide-module#16
wrappid/core#65
wrappid/core#69

**Comment by techoneel** [comment]
toc component built and working closing this issue since the reference is given
