### ISSUE TITLE
bug: CoreImageBackground valid props missing

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/core#72]
**Describe the bug**
Valid props missing, source is not passing to NativeImageBackground component.

**To Reproduce**
Use CoreImageBackground with source props.

**Expected behavior**
Source prop working with CoreImageBackground. 

**Stack Trace**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit
 - Browser: Firefox, Chromium

**Additional context**
Add valid props

**Comment by techoneel** [comment]
update the issue and progress of the bug

**Comment by irkfaisal** [comment]
props has been added and component working fine
