### ISSUE TITLE
docs: Add MIT License in core

### ISSUE THREAD

**Issue by techoneel** [wrappid/core#75]
- [x] Create a LICENSE file from GitHub WebView in **main** branch
- [x] Choose a license template > **MIT License**
- [x] Click on **Review and submit**
- [x] Click on **Commit changes**
- [x] Change commit message in the dialog **Propose changes** window
 ```
docs: 🔒 license added
   
added MIT License as requested

Ref #[issue-number]
```
- [x] Change new branch name as WRPD-docs-[issue-number] in the dialog **Propose changes** window
- [x] Open a pull request to development branch

**Comment by techoneel** [comment]
all the tasks completed and raise a pull request [here](https://github.com/wrappid/core/pull/77).

**Comment by anantakumarghosh** [comment]
closing as merged

**Comment by anantakumarghosh** [comment]
- [ ] add contact and homepage in package.json

**Comment by techoneel** [comment]
Please format package.json @anantakumarghosh

**Comment by anantakumarghosh** [comment]
> * [ ]  add contact and homepage in package.json

- [ ]  add contact
- [ ]  add homepage
- [ ]  add License

**Comment by anantakumarghosh** [comment]
> > * [ ]   add contact and homepage in package.json
> 
>     * [ ]   add contact
> 
>     * [ ]   add homepage
> 
>     * [ ]   add License

Created a separate issue for this mentioned above.

Closing Issue 75 as done
