### ISSUE TITLE
Generate and manually add ATTRIBUTION file in core

### ISSUE THREAD

**Issue by techoneel** [wrappid/core#76]
### Problem
Need to create a list of third-party packages used in our repository (include all [main/dev/peer] dependencies).

### Solution
Use the following package to generate.
License Checker - https://www.npmjs.com/package/license-checker
- Must have a npm script in package.json to generate attribution(s).

### The content of the each item should looks like as follows:
This project uses the following open source software (OSS) components:
[**Package Name**]: [**Copyright holder(s)**] ([**License**]) ([**Package Homepage URL**])
> - Replace [Package Name] with the actual name of the package.
> - Replace [Copyright holder(s)] with the name(s) of the copyright holder(s), as listed in the package's license.
> - Replace [License] with the name of the license under which the package is released.
> - Replace [Package Homepage URL] with a link to the package's website or the specific license text.

**Comment by anantakumarghosh** [comment]
Added scripts to generate attribution. Closing as done.

**Comment by anantakumarghosh** [comment]
@irkfaisal 
https://github.com/wrappid/core/blob/development/scripts/attributions.gen.js
Above script needs to be modified.
Below header will be present in top of attribution file.

## ATTRIBUTIONS

This file lists the third-party libraries, frameworks, and other components used in the [REPOSITORY-NAME] repository,
along with their respective licenses.   
It is important to comply with the licensing terms of these components when using the code

**Comment by anantakumarghosh** [comment]
Closing as done.
