### ISSUE TITLE
docs: Spelling and grammatical mistakes in the guide documentation

### ISSUE THREAD

**Issue by aitijhyasarkar** [wrappid/core#97]
**Describe the bug**
While creating a sample static page, I observed spelling mistakes and grammatical errors in the documentation of both components and styles. This issue is related to https://github.com/wrappid/guide-module/issues/15

**Expected behavior**
All documentations must be thoroughly checked for any silly mistakes like these. Documentations must showcase professionalism.

**Screenshots**
The issues screenshots are all together available in [this zip](https://github.com/wrappid/guide-module/files/14112132/Guide.Modules.grammar.spelling.mistakes.zip)

[Here you can use command tree /F in cmd for listing all files/screenshots for convinience and dir {many}*.png /s /b to list the png files which are repeated multiple times in the documentation]

**Additional context**
- Documentation URLs:
    - [localhost:xxxx/guide/components](https://github.com/wrappid/guide-module/issues/15#)
    - [localhost:xxxx/guide/styles](https://github.com/wrappid/guide-module/issues/15#)
    
**Note:** Ensure that the placeholders xxxx are replaced with the hosted port number.

**Comment by techoneel** [comment]
Closing this similar issue in https://github.com/wrappid/guide-module/issues/15#issuecomment-1923386664
